### ISSUE TITLE
particlex的一些问题

### ISSUE THREAD

**Issue by Aircraft-carrier** [Revethere/Revethere.github.io#1]
<img width="1176" alt="image" src="https://github.com/Revethere/Revethere.github.io/assets/122367292/45628c20-58e9-4572-98c0-8ee5434d7fc0">
我的页面更宽，且代码块不能分行，不清楚你有没有遇到过类似的问题

**Comment by Revethere** [comment]
但是我之前翻了一下早期的版本，不知道是什么原因反正是从某个时间开始代码块的渲染就有问题了...

**Comment by Aircraft-carrier** [comment]
好的谢谢你

**Comment by Revethere** [comment]
> 好的谢谢你

Arg已经有半年没更博客了...

目前不太指望能修复这个 bug（但是应该是本地文件的问题，可以对照以前的版本看一下是哪段导致的问题）

如果可以话就暂时忍受一下？毕竟其它很多主题没这么好看😄

**Comment by Aircraft-carrier** [comment]
哈哈我去回溯一下各个版本试一试

**Comment by Revethere** [comment]
> 哈哈我去回溯一下各个版本试一试

如果弄好了也给我说一声，我已经小半年没拿到电脑了/kk

**Comment by Aircraft-carrier** [comment]
我解决了，我是在根目录下的_yml没有修改导致
<img width="408" alt="image" src="https://github.com/Revethere/Revethere.github.io/assets/122367292/70901e4f-9d6a-4b7d-877f-5a3d16cae14c">

**Comment by Revethere** [comment]
> 我解决了，我是在根目录下的_yml没有修改导致 <img alt="image" width="408" src="https://private-user-images.githubusercontent.com/122367292/345458869-70901e4f-9d6a-4b7d-877f-5a3d16cae14c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMTY3MzUsIm5iZiI6MTcyMDAxNjQzNSwicGF0aCI6Ii8xMjIzNjcyOTIvMzQ1NDU4ODY5LTcwOTAxZTRmLTlkNmEtNGI3ZC04NzdmLTVhM2QxNmNhZTE0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QxNDIwMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YTVkMjIwMDJkZGJlNTJlY2E5NTZiZjE3MTc5NzRlZTJhMmYzY2YyY2ZlYTM3ODliMzJkOTUxMDFlZmU1ZjdkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-DCaelDpBdpWdQDW339HJj58ufSO_mwEUvWOyzG8lJM">

😘
